env:
  _JAVA_OPTIONS="-Xms1G -Xmx4G"

language: java

jdk:
  - oraclejdk9
  - oraclejdk8
  - oraclejdk7
  - openjdk7

addons:
  apt:
    packages:
      - oracle-java8-installer

install: true

script:
  - mvn clean verify

